"""add authentication tables

Revision ID: 4902499eb31c
Revises: cb44cd586cfc
Create Date: 2026-08-21 21:39:26.290663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4902499eb31c'
down_revision: Union[str, Sequence[str], None] = 'cb44cd586cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_records')),
    sa.UniqueConstraint('slug', name=op.f('uq_organization_records_slug'))
    )
    op.create_table('user_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_records.id'], name=op.f('fk_user_records_organization_id_organization_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_records')),
    sa.UniqueConstraint('email', name='uq_user_records_email')
    )
    op.create_index(op.f('ix_user_records_email'), 'user_records', ['email'], unique=True)
    op.create_index('ix_user_records_organization_email', 'user_records', ['organization_id', 'email'], unique=False)
    op.create_index(op.f('ix_user_records_organization_id'), 'user_records', ['organization_id'], unique=False)
    op.create_table('refresh_token_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('token_id', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_records.id'], name=op.f('fk_refresh_token_records_organization_id_organization_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_records.id'], name=op.f('fk_refresh_token_records_user_id_user_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token_records'))
    )
    op.create_index(op.f('ix_refresh_token_records_organization_id'), 'refresh_token_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_records_token_hash'), 'refresh_token_records', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_token_records_token_id'), 'refresh_token_records', ['token_id'], unique=True)
    op.create_index(op.f('ix_refresh_token_records_user_id'), 'refresh_token_records', ['user_id'], unique=False)
    op.create_index('ix_refresh_token_records_user_org', 'refresh_token_records', ['user_id', 'organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_token_records_user_org', table_name='refresh_token_records')
    op.drop_index(op.f('ix_refresh_token_records_user_id'), table_name='refresh_token_records')
    op.drop_index(op.f('ix_refresh_token_records_token_id'), table_name='refresh_token_records')
    op.drop_index(op.f('ix_refresh_token_records_token_hash'), table_name='refresh_token_records')
    op.drop_index(op.f('ix_refresh_token_records_organization_id'), table_name='refresh_token_records')
    op.drop_table('refresh_token_records')
    op.drop_index(op.f('ix_user_records_organization_id'), table_name='user_records')
    op.drop_index('ix_user_records_organization_email', table_name='user_records')
    op.drop_index(op.f('ix_user_records_email'), table_name='user_records')
    op.drop_table('user_records')
    op.drop_table('organization_records')
    # ### end Alembic commands ###
