"""create organization membership records

Revision ID: 6ff2b0500002
Revises: 4902499eb31c
Create Date: 2026-08-22 23:55:57.667990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff2b0500002'
down_revision: Union[str, Sequence[str], None] = '4902499eb31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_membership_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_records.id'], name=op.f('fk_organization_membership_records_organization_id_organization_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_records.id'], name=op.f('fk_organization_membership_records_user_id_user_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_membership_records')),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_organization_membership_org_user')
    )
    op.create_index('ix_organization_membership_org_active', 'organization_membership_records', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_organization_membership_records_organization_id'), 'organization_membership_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_membership_records_user_id'), 'organization_membership_records', ['user_id'], unique=False)
    op.create_index('ix_organization_membership_user_active', 'organization_membership_records', ['user_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organization_membership_user_active', table_name='organization_membership_records')
    op.drop_index(op.f('ix_organization_membership_records_user_id'), table_name='organization_membership_records')
    op.drop_index(op.f('ix_organization_membership_records_organization_id'), table_name='organization_membership_records')
    op.drop_index('ix_organization_membership_org_active', table_name='organization_membership_records')
    op.drop_table('organization_membership_records')
    # ### end Alembic commands ###
