"""create document registry tables

Revision ID: cb44cd586cfc
Revises: 
Create Date: 2026-08-13 16:20:48.707096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb44cd586cfc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('embedding_provider', sa.String(length=64), nullable=True),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('vector_store_provider', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_records')),
    sa.UniqueConstraint('organization_id', 'user_id', 'knowledge_base_id', 'file_hash', name='uq_document_owner_knowledge_base_hash')
    )
    op.create_index('ix_document_owner_knowledge_base', 'document_records', ['organization_id', 'user_id', 'knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_document_records_status'), 'document_records', ['status'], unique=False)
    op.create_table('document_chunk_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_record_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('vector_id', sa.String(length=64), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_record_id'], ['document_records.id'], name=op.f('fk_document_chunk_records_document_record_id_document_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunk_records')),
    sa.UniqueConstraint('vector_id', name='uq_document_chunk_vector_id')
    )
    op.create_index('ix_document_chunk_document_page', 'document_chunk_records', ['document_record_id', 'page_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunk_document_page', table_name='document_chunk_records')
    op.drop_table('document_chunk_records')
    op.drop_index(op.f('ix_document_records_status'), table_name='document_records')
    op.drop_index('ix_document_owner_knowledge_base', table_name='document_records')
    op.drop_table('document_records')
    # ### end Alembic commands ###
